# Generated by Django 4.1.7 on 2023-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imagecaption_created_at_alter_imagecaption_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecaption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
